import React from 'react';
import {StyleSheet,View,Text,ScrollView,ActivityIndicator, Image, TouchableOpacity,Share} from 'react-native';
import * as firebase from 'firebase';

export default class Singup extends React.Component {
state = {
code:'',
loading:true
}


  componentDidMount(){
    const ref = firebase.storage().ref().child(this.props.email + "/" + this.props.sname +"-code.js");
    const that = this;
    ref.getDownloadURL().then(function(data) {
     
        fetch(data)
        .then(function(response) {
          response.text().then(function(text) {
            that.setState({ code: text,
                            loading: false
                          });
          });
        });
      }).catch(function(error) {
          console.log(error);
      });
  }
  componentWillUnmount() {
  
  }
  shareEvent=()=>{
    console.log("Floating Button Clicked");
    try {
        const result = Share.share({
          message: this.state.code,
          title: 'Layout: ' + this.props.sname + ' - code generated by Sketch ML'
        })
  
        if (result.action === Share.sharedAction) {
          if (result.activityType) {
            // shared with activity type of result.activityType
          } else {
            // shared
          }
        } else if (result.action === Share.dismissedAction) {
          // dismissed
        }
      } catch (error) {
        alert(error.message);
      }
  }
  
    render(){
        const isLoading = this.state.loading;
            return(
                <View style={styles.container}>
                {isLoading ? (
                   	<View style={styles.container}>
                      <ActivityIndicator size="large" color="#66BB6A" />
                    </View>
                ) : (
                <View style={styles.container}>
                    <ScrollView>
                        <Text
                        style={styles.code}
                        selectable={true} 
                        >{this.state.code}</Text>
                    </ScrollView>
                    <TouchableOpacity 
                    activeOpacity={0.5} 
                    style={styles.TouchableOpacityStyle}
                    onPress={this.shareEvent}  >
                        <Image source={require('../assets/share.png')}  style={styles.FloatingButtonStyle} />
                    </TouchableOpacity>
                </View>
                )}
               </View>
                );
    }//end of render method

}//end of class

const styles = StyleSheet.create({
    container: {
      justifyContent: 'center',
      
    },
    code: {
      fontFamily: 'monospace',
      fontSize: 12
    },
    TouchableOpacityStyle: {
      position: 'absolute',
      width: 50,
      height: 50,
      alignItems: 'center',
      justifyContent: 'center',
      right: 20,
      bottom: 20,
      backgroundColor:'#66BB6A',
      borderRadius: 64,
      shadowColor: 'rgba(0,0,0, .4)', // IOS
      shadowOffset: { height: 1, width: 1 }, // IOS
      shadowOpacity: 1, // IOS
      shadowRadius: 1, //IOS
      elevation: 5 // Android
    },
    FloatingButtonStyle: {
      resizeMode: 'contain',
      width: 30,
      height: 30,
      marginRight:3
    },
 })